receivers:
  otlp:
    protocols:
      grpc:
  opencensus:
  jaeger:
    protocols:
      grpc:
      thrift_http:
  zipkin:

exporters:
  otlp:
    endpoint: "otel-collector:4317"
    insecure: true
  logging:
    loglevel: debug
  site24x7file:
    path: /home/data/agent.json
    url: http://Shrini-2027/arh/opentelemetry
  #  url: https://catalyst.localsite24x7.com/arh/opentelementry

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [otlp, logging,site24x7file]
    metrics:
      receivers: [otlp, opencensus]
      processors: [batch]
      exporters: [otlp, logging,site24x7file]
